import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script src="/botao.js" defer></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header >
        <h2 className={styles.logo}>Logo</h2>
        <nav className={styles.navagar}>
          <a href="#">Home</a>
          <a href="#">Contatos</a>
          <a href="#">Sobre</a>
          <a href="#">Info</a>
        </nav>
      </header>
      <div className={styles.log}>
        <div className={styles.boxlog}>
          <h2 className={styles.hlogin}>Login</h2>
          <div className={styles.inputlog}>
            <input type="email" />
            <label>E-mail</label>
          </div>
            <div className={styles.inputlog}>
              <input type="password" />
              <label>Senha</label>
            </div>
            <div className={styles.check}>
              <label  style={{
                marginRight:"30px",
              }}>
                <input  type="checkbox" />
                Manter login
              </label>
              <a style={{
                color:"#ed83ff",
                textDecoration:"none"
              }} href="#">Esqueceu a senha?</a>
            </div>
            <button className={styles.entrar}>Login</button>
            </div>
            </div>
            
    </>
  )
}
